language: python

python:
  - "2.7"

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8
  - pip install awscli awsebcli

before_script:
  - flake8
  - docker-compose up -d db
  - docker-compose run core setuplocaldb

script:
  - docker-compose run core test_coverage


