version: '2'
services:
    db:
        image: "postgres:9.5.2"

    core:
        build: sift-core
        environment:
            RDS_HOSTNAME: "db"
            RDS_USERNAME: "postgres"
            RDS_PASSWORD: ""
            RDS_PORT: ""
            RDS_DB_NAME: "sift"
            STATIC_ROOT: "/var/www/static/"
        volumes:
            - ./sift-core:/code
            - ./core_home:/root/
        hostname: siftcore-app
        ports:
            - "8000:8000"
        links:
            - db

    odk-importer:
        build: sift-odk-importer
        environment:
            RDS_HOSTNAME: "db"
            RDS_USERNAME: "postgres"
            RDS_PASSWORD: ""
            RDS_PORT: ""
            RDS_DB_NAME: "odk_importer"
            STATIC_ROOT: "/var/www/static/"
        volumes:
            - ./sift-odk-importer:/code
            - ./importer_home:/root/
        ports:
            - "8443:8443"
        links:
            - core
            - db